<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ST10" Id="{61144e30-0e02-44e4-a1c9-c2000a6e1c68}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ST10
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ST10">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>