<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5a8e1327-26d3-4e43-8559-97c135f86653}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_fb : FB_ST10; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_fb._scanner();
_fb.stole:= true; ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>